version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: socialAppDb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
volumes:
  mongodb: ~
